### ISSUE TITLE
Requires files in the dataset

### ISSUE THREAD

**Issue by thebigeagle** [gpt4vision/OvSGTR#10]
Thank you very much for publishing your code, but can you provide the files in the coco dataset? That is, captions_train2017_triple.json and captions_val2017_triple.json

**Comment by JosephChenHub** [comment]
> Thank you very much for publishing your code, but can you provide the files in the coco dataset? That is, captions_train2017_triple.json and captions_val2017_triple.json

hi, I have uploaded these two files, please see the updated [data.md](https://github.com/gpt4vision/OvSGTR/blob/master/datasets/data.md)
