### ISSUE TITLE
RROR: modelname:groundingdino not in models:{}

### ISSUE THREAD

**Issue by ZMH-SDUST** [gpt4vision/OvSGTR#12]
File "main.py", line 103, in build_model_main
    assert args.modelname in MODULE_BUILD_FUNCS._module_dict, "ERROR: modelname:{} not in models:{}".format(args.modelname, MODULE_BUILD_FUNCS._module_dict)
AssertionError: ERROR: modelname:groundingdino not in models:{}

**Comment by JosephChenHub** [comment]
> File "main.py", line 103, in build_model_main assert args.modelname in MODULE_BUILD_FUNCS._module_dict, "ERROR: modelname:{} not in models:{}".format(args.modelname, MODULE_BUILD_FUNCS._module_dict) AssertionError: ERROR: modelname:groundingdino not in models:{}

please refer to the installation
