### ISSUE TITLE
Quick Question : why not normalize the output of relation feature ? (OVR or OVD + R setting)

### ISSUE THREAD

**Issue by LimGeunTaekk** [gpt4vision/OvSGTR#19]
Thank you for sharing such excellent work! 

I have a question regarding one of the implementations. 

In the context of OVR or OVD+R, it seems that the **relation feature isn't normalized after passing through the MLP** when performing alignment between the relation feature and the text feature. 

Why does it work? Did I miss something?

Could you clarify this?"

![image](https://github.com/user-attachments/assets/23b9313b-3815-4b40-932e-94acad2e3946)

**Comment by JosephChenHub** [comment]
> Thank you for sharing such excellent work!
> 
> I have a question regarding one of the implementations.
> 
> In the context of OVR or OVD+R, it seems that the **relation feature isn't normalized after passing through the MLP** when performing alignment between the relation feature and the text feature.
> 
> Why does it work? Did I miss something?
> 
> Could you clarify this?"
> 
> ![image](https://private-user-images.githubusercontent.com/70448161/384264823-23b9313b-3815-4b40-932e-94acad2e3946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTUyNDUsIm5iZiI6MTczMTA1NDk0NSwicGF0aCI6Ii83MDQ0ODE2MS8zODQyNjQ4MjMtMjNiOTMxM2ItMzgxNS00YjQwLTkzMmUtOTRhY2FkMmUzOTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA4MzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZmY0ODVjZGM0MTExYWYyNDUzOGJmNTE1OGIxMzFkYjdlM2YyNDMwNzdmYTJmM2NhZDg5OWQwMjIyZmNmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x6zQYolHsajhLesT0btbpc-yHGmXiTfLnsL8iFmGHY4)

there is no need to normalise the value as sigmoid loss/ focal loss is used.

**Comment by LimGeunTaekk** [comment]
Oh, you're right! Thanks for the response
