### ISSUE TITLE
Hello, can you provide the vg_stats.pt # frequency bias in the data  ├─ zeroshot_triplet.pytorch and ├─ VG-SGG-dicts.json # add split_GLIPunseen  ├─ VG-SGG.h5

### ISSUE THREAD

**Issue by CarlBruce** [gpt4vision/OvSGTR#2]
Hello, can you provide the vg_stats.pt # frequency bias in the data 
├─ zeroshot_triplet.pytorch and ├─ VG-SGG-dicts.json # add split_GLIPunseen 
├─ VG-SGG.h5

**Comment by JosephChenHub** [comment]
> Hello, can you provide the vg_stats.pt # frequency bias in the data ├─ zeroshot_triplet.pytorch and ├─ VG-SGG-dicts.json # add split_GLIPunseen ├─ VG-SGG.h5

hi, I have updated the links in https://github.com/gpt4vision/OvSGTR/blob/master/datasets/data.md

**Comment by CarlBruce** [comment]
您好，邮件收悉，我会尽快回复的。
