### ISSUE TITLE
Results in Table 5

### ISSUE THREAD

**Issue by qwerhk839** [gpt4vision/OvSGTR#21]
I would like to know which config file was used to test the table5 results?

**Comment by qwerhk839** [comment]
I use the "GroundingDINO_SwinT_OGC_pretrain.py" to test the performance on VG dataset of vg-pretrain-coco-swint.pth, the performance is higher than table 5 (even higher than trained on COCO+Flickr30k+SBU). So I want to know if the config file is used incorrectly or if this ckpt uses more than the coco dataset for pretraining. Thank you :>

<img width="1370" alt="image" src="https://github.com/user-attachments/assets/5d6c9ee7-36d1-4d45-b2d4-c9e29c6757c2">

**Comment by UndineX** [comment]
> > I use the "GroundingDINO_SwinT_OGC_pretrain.py" to test the performance on VG dataset of vg-pretrain-coco-swint.pth, the performance is higher than table 5 (even higher than trained on COCO+Flickr30k+SBU). So I want to know if the config file is used incorrectly or if this ckpt uses more than the coco dataset for pretraining. Thank you :>
> > <img alt="image" width="1370" src="https://private-user-images.githubusercontent.com/183676585/390704286-5d6c9ee7-36d1-4d45-b2d4-c9e29c6757c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTA4MTYsIm5iZiI6MTczMzE5MDUxNiwicGF0aCI6Ii8xODM2NzY1ODUvMzkwNzA0Mjg2LTVkNmM5ZWU3LTM2ZDEtNGQ0NS1iMmQ0LWM5ZTI5YzY3NTdjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMTQ4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2ZhMzkzMjg4ODI0OWM0M2MzZGZkMmJiYjczNDkwOGIyNjc4NGFkOTJhNGRhZDYxZGRmZDY2YTUxNjFmOTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DFeM7ndoMJzfRkImPgvya8gdNiQFS5oSSqzuT4Wmgxg">
> 
> I think I have answered your question in the email .

Can you tell us the reason?
