### ISSUE TITLE
Can not run your code successfully

### ISSUE THREAD

**Issue by hnczgytmp** [gpt4vision/OvSGTR#3]
Thanks for your great work!
```
File "/home/zywang/Documents/code/OvSGTR/datasets/sgg_eval.py", line 193, in update_coco
    coco_dt = COCO.loadRes(self.coco_gt, coco_res) if coco_res else COCO()
  File `"/home/zywang/anaconda3/envs/OvSGTR/lib/python3.9/site-packages/pycocotools/coco.py",` line 334, in loadRes
    elif 'bbox' in anns[0] and not anns[0]['bbox'] == []:
ValueError: operands could not be broadcast together with shapes (4,) (0,)
```
When executing your scripts with the command `bash scripts/DINO_train_dist.sh vg ./config/GroundingDINO_SwinT_OGC_full.py ./data ./logs/ovsgtr_vg_swint_full ./GroundingDINO/weights/groundingdino_swint_ogc.pth`, I encountered the above issues. It appears that there are issues within the inference code and I haven't made any changes to the original code. Could you please investigate this matter? 
Thanks!

**Comment by JosephChenHub** [comment]
> Thanks for your great work!
> 
> ```
> File "/home/zywang/Documents/code/OvSGTR/datasets/sgg_eval.py", line 193, in update_coco
>     coco_dt = COCO.loadRes(self.coco_gt, coco_res) if coco_res else COCO()
>   File `"/home/zywang/anaconda3/envs/OvSGTR/lib/python3.9/site-packages/pycocotools/coco.py",` line 334, in loadRes
>     elif 'bbox' in anns[0] and not anns[0]['bbox'] == []:
> ValueError: operands could not be broadcast together with shapes (4,) (0,)
> ```
> 
> When executing your scripts with the command `bash scripts/DINO_train_dist.sh vg ./config/GroundingDINO_SwinT_OGC_full.py ./data ./logs/ovsgtr_vg_swint_full ./GroundingDINO/weights/groundingdino_swint_ogc.pth`, I encountered the above issues. It appears that there are issues within the inference code and I haven't made any changes to the original code. Could you please investigate this matter? Thanks!

could you provide more details ?
