### ISSUE TITLE
Problem with config file

### ISSUE THREAD

**Issue by SIST-wangchongyu** [gpt4vision/OvSGTR#4]
Hello, I am a bit confused about the configuration settings in the config file while performing the OVR experiment setup for model training. Should unsupervised_distill in the config file be set to true? I found that when I set it to true, the recall performance of the model for novel relations is 0. However, if I set it to false, the performance is quite good. Below is the performance graph.
![c66da2f9ff20f38f04b46fc1764f085f](https://github.com/user-attachments/assets/ef6403fa-10f4-47f4-9631-81d636910b2f)

**Comment by JosephChenHub** [comment]
> Hello, I am a bit confused about the configuration settings in the config file while performing the OVR experiment setup for model training. Should unsupervised_distill in the config file be set to true? I found that when I set it to true, the recall performance of the model for novel relations is 0. However, if I set it to false, the performance is quite good. Below is the performance graph. ![c66da2f9ff20f38f04b46fc1764f085f](https://private-user-images.githubusercontent.com/77949448/352127486-ef6403fa-10f4-47f4-9631-81d636910b2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNDY1MzMsIm5iZiI6MTcyMjA0NjIzMywicGF0aCI6Ii83Nzk0OTQ0OC8zNTIxMjc0ODYtZWY2NDAzZmEtMTBmNC00N2Y0LTk2MzEtODFkNjM2OTEwYjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDAyMTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMzg4MTI4OWI3M2M1NmYzZWZmYmVkY2Q1MTJhOTk1ZTRhYjI2M2NmMzE3MDA5N2RjMTM0MmY2YzcxMTMzMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xdLflMUwnCUj-c-lcaClO2nOn45dA4RH4YKJxFj3t_A)

Hi, I have updated the config file. The unsupervised_distill should be set to True for OvR exp.
