### ISSUE TITLE
ECCV 2024 cam-ready version

### ISSUE THREAD

**Issue by LimGeunTaekk** [gpt4vision/OvSGTR#5]
Congratulations on having your paper accepted at ECCV 2024, and thank you for sharing your excellent research.

It seems that the version currently on arXiv is not the ECCV 2024 submission version. Could you let me know when you plan to update it?

It would be greatly appreciated if you could update the final version on arXiv when it is ready.

**Comment by JosephChenHub** [comment]
> Congratulations on having your paper accepted at ECCV 2024, and thank you for sharing your excellent research.
> 
> It seems that the version currently on arXiv is not the ECCV 2024 submission version. Could you let me know when you plan to update it?
> 
> It would be greatly appreciated if you could update the final version on arXiv when it is ready.

Hi, I have uploaded the [camera-ready version](https://github.com/gpt4vision/OvSGTR/tree/master/paper/). The arXiv version will be updated when the final version has been printed by Springer.

**Comment by LimGeunTaekk** [comment]
Thank you for your quick reply, and congratulations once again. I believe your work will serve as a great inspiration for my future research as well! Thanks a lot!
