### ISSUE TITLE
Links in Dataset Instructions not properly set

### ISSUE THREAD

**Issue by kochsebastian** [gpt4vision/OvSGTR#6]
In `datasets/data.md`:
"you can directly download the data from huggingface [link](https://github.com/gpt4vision/OvSGTR/blob/master/datasets) and ignore the following steps": The link points to -> [https://github.com/gpt4vision/OvSGTR/blob/master/datasets](https://github.com/gpt4vision/OvSGTR/blob/master/datasets) could update it with the correct link?
Likewise: "(please refer to [tools/cleaned_split_GLIPunseen.ipynb](https://github.com/gpt4vision/OvSGTR/blob/master/datasets/tools/cleaned_split_GLIPunseen.ipynb)" points to -> [https://github.com/gpt4vision/OvSGTR/blob/master/datasets/tools/cleaned_split_GLIPunseen.ipynb](https://github.com/gpt4vision/OvSGTR/blob/master/datasets/tools/cleaned_split_GLIPunseen.ipynb) and results in file not found. Please update it.

Also, could you provide the file `vg_stats.pt` directly or provide a minimal working example to generate the file. The reference you provided is not really helpful as it requires setting up an entirely different project from scratch.

**Comment by JosephChenHub** [comment]
> In `datasets/data.md`: "you can directly download the data from huggingface [link](https://github.com/gpt4vision/OvSGTR/blob/master/datasets) and ignore the following steps": The link points to -> https://github.com/gpt4vision/OvSGTR/blob/master/datasets could update it with the correct link? Likewise: "(please refer to [tools/cleaned_split_GLIPunseen.ipynb](https://github.com/gpt4vision/OvSGTR/blob/master/datasets/tools/cleaned_split_GLIPunseen.ipynb)" points to -> https://github.com/gpt4vision/OvSGTR/blob/master/datasets/tools/cleaned_split_GLIPunseen.ipynb and results in file not found. Please update it.
> 
> Also, could you provide the file `vg_stats.pt` directly or provide a minimal working example to generate the file. The reference you provided is not really helpful as it requires setting up an entirely different project from scratch.

hi , I have updated the data.md
