### ISSUE TITLE
Clarification on the Generation of image_data.json, VG-SGG-dicts.json, and VG-SGG.h5 for VG150

### ISSUE THREAD

**Issue by zhuhl0913** [gpt4vision/OvSGTR#7]
Hi,

I'm currently preparing the VG150 dataset according to the instructions provided in [OvSGTR's dataset preparation guide](https://github.com/gpt4vision/OvSGTR/blob/master/datasets/data.md). I have successfully downloaded the VG images and the scene graphs (specifically `VG-SGG-with-attri.h5`) and placed them in the correct directories as specified.

However, I am unsure about the generation of the following files that are mentioned under "The dataset is organized as" section:
- `image_data.json`
- `VG-SGG-dicts.json`
- `VG-SGG.h5`

Could you please clarify how these files are generated? Are there specific scripts or preprocessing steps that I need to follow? I could not find detailed information regarding the generation of these files in the current documentation.

Thanks for your help!

**Comment by JosephChenHub** [comment]
> Hi,
> 
> I'm currently preparing the VG150 dataset according to the instructions provided in [OvSGTR's dataset preparation guide](https://github.com/gpt4vision/OvSGTR/blob/master/datasets/data.md). I have successfully downloaded the VG images and the scene graphs (specifically `VG-SGG-with-attri.h5`) and placed them in the correct directories as specified.
> 
> However, I am unsure about the generation of the following files that are mentioned under "The dataset is organized as" section:
> 
> * `image_data.json`
> * `VG-SGG-dicts.json`
> * `VG-SGG.h5`
> 
> Could you please clarify how these files are generated? Are there specific scripts or preprocessing steps that I need to follow? I could not find detailed information regarding the generation of these files in the current documentation.
> 
> Thanks for your help!

please see the updated information
