### ISSUE TITLE
Cannot import name '_C' from 'groundingdino'

### ISSUE THREAD

**Issue by zhuhl0913** [gpt4vision/OvSGTR#9]
That's a problem I met when running inference script in OVR setting with swin_t checkpoint. It has something to do with./models/GroundingDINO/ms_deform_attn.py. But I found a comment in GroundDino's issue that fix that problem.:
https://github.com/IDEA-Research/GroundingDINO/issues/8#issuecomment-1541892708

**Comment by JosephChenHub** [comment]
> That's a problem I met when running inference script in OVR setting with swin_t checkpoint. It has something to do with./models/GroundingDINO/ms_deform_attn.py. But I found a comment in GroundDino's issue that fix that problem.: [IDEA-Research/GroundingDINO#8 (comment)](https://github.com/IDEA-Research/GroundingDINO/issues/8#issuecomment-1541892708)

Generally, this error can be fixed by re-compiling the src code.  Have you ever solved this issue?

**Comment by zhuhl0913** [comment]
Yes, I've fixed this error following the https://github.com/IDEA-Research/GroundingDINO/issues/8#issuecomment-1541892708.
